/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"
#include "uart.h"
#include "led.h"
#include <string.h>
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	SystemInit();
	char str[32];
	int choice;
	UartInit(9600);
	LedInit(LED_RED_PIN);
	LedInit(LED_BLUE_PIN);
	LedInit(LED_ORANGE_PIN);
	LedInit(LED_GREEN_PIN);
	UartPuts("ENTER WHICH LED YOU WANT TO GLOW \r\n");
	UartPuts("1. RED LED ON \r\n 2. BLUE LED ON \r\n 3. ORANGE LED ON \r\n 4. GREENLED ON \r\n");
	while(1)
	{

		UartGets(str);
		sscanf(str,"%d",&choice);
		UartPuts(str);
		switch(choice)
		{
		case 1 : LedBlink(LED_RED_PIN,100);
		         break;
		case 2 : LedBlink(LED_BLUE_PIN,100);
                         break;
		case 3 : LedBlink(LED_ORANGE_PIN,100) ;
		         break;
		case 4 : LedBlink(LED_GREEN_PIN,100) ;
		         break;
		}
		UartPuts(str);
	}
	return 0;
}
