/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"

#include "switch.h"
#include "led.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif



int main(void)
{
	SystemInit();
	ledinit(GPIO_GREEN_PIN);
	ledinit(GPIO_ORANGE_PIN);
	ledinit(GPIO_BLUE_PIN);
	ledinit(GPIO_RED_PIN);
	SwitchInit();

    int i=0;
    while(1)
    {
    	while(flag == 0)
    		 ;
    	for(;i<4;i++)
    	{
    	   ledblink(GPIO_GREEN_PIN+i,1000);
    	}

    	flag=0;
    	i=0;
    }
	return 0;
}
