/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"
#include "accel.h"
#include "i2c.h"
#include"i2c_lcd.h"
#include "led.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void) {
	char str[32];
	char str1[32];
	LIS_Data val;
	Lcd_Init();
	SystemInit();
	LedInit(LED_RED_PIN);
	LedInit(LED_BLUE_PIN);
	LedInit(LED_ORANGE_PIN);
	LedInit(LED_GREEN_PIN);
//	Lcd_Puts(LCD_LINE1,"LIS3DSH Demo!\r\n");
	LIS_Init(); //initialize accel
	while(1) {
		if(LIS_IsDataAvail()) // check if new data avail
		{
			val = LIS_GetData(); // get the new data
			// print value
			sprintf(str, "X=%d, Y=%d\r\n", val.x, val.y);
			sprintf(str1, "z=%d\r\n", val.z);
			DelayMs(500);
			Lcd_Puts(LCD_LINE1,str);
			Lcd_Puts(LCD_LINE2,str1);

			if(val.x >=3000)
			{
				LedOn(LED_RED_PIN);
			}
			else
			{

				LedOff(LED_RED_PIN);
				DelayMs(50);
			}
			if(val.x >=3000)
						{
							LedOn(LED_BLUE_PIN);
						}
						else
						{

							LedOff(LED_BLUE_PIN);
							DelayMs(50);
						}
			if(val.x >=3000)
						{
							LedOn(LED_ORANGE_PIN);
						}
						else
						{

							LedOff(LED_ORANGE_PIN);
							DelayMs(50);
						}
			if(val.x >=3000)
						{
							LedOn(LED_GREEN_PIN);
						}
						else
						{

							LedOff(LED_GREEN_PIN);
							DelayMs(50);
						}
		}

	}
	return 0;
}
